/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TrustworthyRockPaperScissorsTournament__factory } from "./TrustworthyRockPaperScissorsTournament__factory";
export { TrustworthyRockPaperScissorsTournamentGenerator__factory } from "./TrustworthyRockPaperScissorsTournamentGenerator__factory";
export { TrustworthyRockPaperScissorsTournamentSpecs__factory } from "./TrustworthyRockPaperScissorsTournamentSpecs__factory";
