/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TrustworthyRockPaperScissorsTournamentSpecs,
  TrustworthyRockPaperScissorsTournamentSpecsInterface,
} from "../TrustworthyRockPaperScissorsTournamentSpecs";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "enum TrustworthyRockPaperScissorsTournamentSpecs.Player",
        name: "winner",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "numMatch",
        type: "uint8",
      },
    ],
    name: "MatchWonBy",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "enum TrustworthyRockPaperScissorsTournamentSpecs.Player",
        name: "winner",
        type: "uint8",
      },
    ],
    name: "TournamentWonBy",
    type: "event",
  },
  {
    inputs: [],
    name: "disputedMatches",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "movePaper",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "moveRock",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "moveScissor",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class TrustworthyRockPaperScissorsTournamentSpecs__factory {
  static readonly abi = _abi;
  static createInterface(): TrustworthyRockPaperScissorsTournamentSpecsInterface {
    return new utils.Interface(
      _abi
    ) as TrustworthyRockPaperScissorsTournamentSpecsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TrustworthyRockPaperScissorsTournamentSpecs {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TrustworthyRockPaperScissorsTournamentSpecs;
  }
}
